name: Docker image for Satisfactory dedicated server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: docker build setup
        uses: docker/setup-buildx-action@v1

      - name: docker hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: build and push image to docker hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: abalchiumas/s10y-server:latest